[distrax] Fix shape bug in mc_estimate_mode for non-scalar events.
Distributions which return non-scalar events require broadcasting of the mode-index derived from the log-prob.

The bug can be reproduced using:
distribution = distrax.MultivariateNormalDiag(loc=np.ones((4, 5, 20)))
distrax.mc_estimate_mode(distribution, rng_key=42, num_samples=10)
> ValueError: indices and arr must have the same number of dimensions; 3 vs. 4
PiperOrigin-RevId: 430180110